export const SET_LOCATION_INPUT = "SET_LOCATION_INPUT";
export const RECEIVE_LOCATIONS = "RECEIVE_LOCATIONS";

export const SET_DEFAULT_DATES = "SET_DEFAULT_DATES";
export const SET_FOCUSED_INPUT = "SET_FOCUSED_INPUT";

export const RECEIVE_PASSENGERS = "RECEIVE_PASSENGERS";
export const SET_PASSENGER_VALUE = "SET_PASSENGER_VALUE";
export const INCREMENT_PASSENGER = "INCREMENT_PASSENGER";
export const DECREMENT_PASSENGER = "DECREMENT_PASSENGER";
export const TOGGLE_INPUT = "TOGGLE_INPUT";

export const LOADING = "LOADING";
